---
target_model:
  architecture: resnet18 # architecture of target model
  num_classes: 530 # number of output neurons
  weights: pretrained/resnet18_facescrub.pt # link to weight file
evaluation_model:
  architecture: inception-v3 # architecture of evaluation model
  num_classes: 530 # number of output neurons
  weights: pretrained/inception_v3_facescrub.pt # link to weight file

logging: True
logging_images: True
name: FaceScrub
stylegan_model: stylegan2_intermediate/ffhq_G.pth # Path to StyleGAN2 weight.
seed: 42 # Seed used for splitting the datasets and initialize the attack.
dataset: facescrub # Target dataset, select one of [facescrub, celeba_identities, stanford_dogs_cropped, stanford_dogs_uncropped].
result_path: results/main/ffhq/resnet

candidates:
  num_candidates: 50 # Number of latent vectors to optimize for each target.
  candidate_search:
    search_space_size: 2000 # Set of randomly sampled latent vector, from which the candidates are selected.
    center_crop: 800 # Crop generated images.
    resize: 224 # Resize generated images (after cropping).
    horizontal_flip: true # Flip the generated images horizontally in 50% of the cases.
    batch_size: 20 # Batch size during the sampling process (single GPU).
    truncation_psi: 0.5 # Truncation psi for StyleGAN.
    truncation_cutoff: 8 # Truncation cutoff for StyleGAN.

attack:
  batch_size: 5 # Batch size per GPU.
  num_epochs: 50 # Number of optimization iterations per batch.
  targets: all # Specify the targeted classes, either a single class index, a list of indices, or all.
  single_w: true # Optimize a single 512-vector. Otherwise, a distinct vector for each AdaIn operation is optimized.
  clip: false # Clip generated images in range [-1, 1].
  transformations: # Transformations applied during the optimization.
    CenterCrop:
      size: 800
    Resize:
      size: 224
      antialias: true
    RandomResizedCrop:
      size: [224, 224]
      scale: [0.9, 1.0]
      ratio: [1.0, 1.0]
      antialias: true

  optimizer: # Optimizer used for optimization. All optimizers from torch.optim are possible.
    Adam:
      lr: 0.005
      weight_decay: 0
      betas: [0.1, 0.1]

intermediate:
  start: 0
  end: 8
  steps: [50,10,10,10,10,10,10,10]
  max_radius_mid_vecor: [1000, 2000, 3000, 4000, 5000, 6000, 8000, 8000]
  max_radius_w: [1000, 2000, 3000, 4000, 5000, 6000, 8000, 8000]